/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package kayttoliittyma;

/**
 *
 * @author s1700306
 */
public class Paavalikko extends javax.swing.JFrame {

    /**
     * Creates new form Paavalikko
     */
    public Paavalikko() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        otsikkoLabel = new javax.swing.JLabel();
        aloitaPeliButton = new javax.swing.JButton();
        saannotButton = new javax.swing.JButton();
        lopetaButton = new javax.swing.JButton();
        haePelitButton = new javax.swing.JButton();
        backgroundLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 0, 51));
        setLocationByPlatform(true);
        setPreferredSize(new java.awt.Dimension(600, 500));
        setResizable(false);
        getContentPane().setLayout(null);

        otsikkoLabel.setFont(new java.awt.Font("Segoe Script", 1, 36)); // NOI18N
        otsikkoLabel.setForeground(new java.awt.Color(153, 255, 153));
        otsikkoLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        otsikkoLabel.setText("Blackjack");
        getContentPane().add(otsikkoLabel);
        otsikkoLabel.setBounds(110, 50, 380, 67);

        aloitaPeliButton.setText("Aloita peli");
        aloitaPeliButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aloitaPeliButtonActionPerformed(evt);
            }
        });
        getContentPane().add(aloitaPeliButton);
        aloitaPeliButton.setBounds(170, 150, 268, 52);

        saannotButton.setText("Säännöt");
        saannotButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saannotButtonActionPerformed(evt);
            }
        });
        getContentPane().add(saannotButton);
        saannotButton.setBounds(170, 220, 268, 50);

        lopetaButton.setText("Lopeta");
        lopetaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lopetaButtonActionPerformed(evt);
            }
        });
        getContentPane().add(lopetaButton);
        lopetaButton.setBounds(170, 360, 268, 53);

        haePelitButton.setText("Pelihistoria");
        haePelitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                haePelitButtonActionPerformed(evt);
            }
        });
        getContentPane().add(haePelitButton);
        haePelitButton.setBounds(170, 290, 270, 50);

        backgroundLabel.setBackground(new java.awt.Color(255, 51, 51));
        backgroundLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kayttoliittyma/Background-Green-1600x1200.png"))); // NOI18N
        backgroundLabel.setPreferredSize(new java.awt.Dimension(592, 520));
        getContentPane().add(backgroundLabel);
        backgroundLabel.setBounds(0, -90, 600, 680);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lopetaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lopetaButtonActionPerformed
    System.exit(0);
    }//GEN-LAST:event_lopetaButtonActionPerformed

    private void saannotButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saannotButtonActionPerformed
    new Saannot().setVisible(true);
    }//GEN-LAST:event_saannotButtonActionPerformed

    private void aloitaPeliButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aloitaPeliButtonActionPerformed
    new Peli().setVisible(true);
    this.dispose();
    }//GEN-LAST:event_aloitaPeliButtonActionPerformed

    private void haePelitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_haePelitButtonActionPerformed
        new Pelihistoria().setVisible(true);
    }//GEN-LAST:event_haePelitButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Paavalikko.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Paavalikko.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Paavalikko.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Paavalikko.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Paavalikko().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aloitaPeliButton;
    private javax.swing.JLabel backgroundLabel;
    private javax.swing.JButton haePelitButton;
    private javax.swing.JButton lopetaButton;
    private javax.swing.JLabel otsikkoLabel;
    private javax.swing.JButton saannotButton;
    // End of variables declaration//GEN-END:variables
}
